### ISSUE TITLE
consider adding GH Action to auto-add PRs and issues to our PACTA board

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/pactaverse#15]
based on https://github.com/RMI-PACTA/pacta.portfolio.allocate/blob/main/.github/workflows/add-prs-and-issues-to-project.yml

**Comment by jdhoffa** [comment]
Is there any way to DRY this? By using https://github.com/RMI-PACTA/.github for example? 

I worry that if we ever have to update that workflow for any reason it's going to be a huge annoying pain in the ass to do it across all our repos.

**Comment by jdhoffa** [comment]
Closing this, as I now track issues on this repo in my personal maintainer board. 

Also noting that we have managed to DRY this (or working towards it anyway) with this https://github.com/RMI-PACTA/actions
