### ISSUE TITLE
feat: merge pacta.sit.rep functionality with this repo, and render the report as a page in the `pkgdown` site

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pactaverse#43]
@cjyetman it might/ probably makes sense to combine https://github.com/RMI-PACTA/pacta.sit.rep with this repo, and render the situation report table as a page in the `pkgdown` site of `pactaverse`, what do you think?

**Comment by cjyetman** [comment]
At the moment, the sit.rep tables require constant manual updates to be actually up-to-date, which I'm not to keen on. If we got it to build a static page that pulls the most recent info whenever it's loaded, then I think it could be useful without being burdensome.

**Comment by jdhoffa** [comment]
Totally! One option could be to only migrate the portion of the `pacta.sit.rep` that are generated statically.
I also notice that some issues are open towards this: https://github.com/RMI-PACTA/pacta.sit.rep/issues/35

Alternatively, we can implement it entirely statically in pacta.sit.rep first, and then migrate it over. 

Just wanted to track the intention to do so in this ticket :-)

**Comment by cjyetman** [comment]
Would this work? It's all static markdown/html, but the values are all dynamic, except for lifecycle which we don't assign in any programmatic way.


| repo | lifecycle | status | coverage | r-universe | CRAN | dev | maintainer |
| ---- | --------- | ------ | -------- | ---------- | ---- | --- | ---------- |
| [pacta.data.scraping](https://rmi-pacta.github.io/pacta.data.scraping/) | [![](https://img.shields.io/badge/lifecycle-stable-none.svg?labelColor=%23444d56&amp;color=%2334d058)](https://lifecycle.r-lib.org/articles/stages.html#stable) | [![](https://github.com/RMI-PACTA/pacta.data.scraping/actions/workflows/R-CMD-check.yaml/badge.svg?branch=main)](https://github.com/RMI-PACTA/pacta.data.scraping/actions/workflows/R-CMD-check.yaml?query=branch%3Amain) | [![](https://img.shields.io/codecov/c/github/rmi-pacta/pacta.data.scraping/main)](https://app.codecov.io/gh/RMI-PACTA/pacta.data.scraping?branch=main) | [![](https://rmi-pacta.r-universe.dev/badges/pacta.data.scraping)](https://rmi-pacta.r-universe.dev/pacta.data.scraping) | [![](https://www.r-pkg.org/badges/version/pacta.data.scraping)](https://CRAN.R-project.org/package=pacta.data.scraping) | [![](https://img.shields.io/github/r-package/v/rmi-pacta/pacta.data.scraping/main?label=version&amp;labelColor=%23444d56&amp;color=%2334d058)](https://github.com/RMI-PACTA/pacta.data.scraping/blob/main/DESCRIPTION) | [![](https://img.shields.io/badge/dynamic/json?label=codeowner&amp;query=codeownerInfo.ownersForFile&amp;url=https%3A%2F%2Fgithub.com%2Frmi-pacta%2Fpacta.data.scraping%2Fdeferred-metadata%2Fmain%2F.github%2FCODEOWNERS)](https://github.com/RMI-PACTA/pacta.data.scraping/blob/main/.github/CODEOWNERS) |
| [pacta.portfolio.import](https://rmi-pacta.github.io/pacta.portfolio.import/) | [![](https://img.shields.io/badge/lifecycle-stable-none.svg?labelColor=%23444d56&amp;color=%2334d058)](https://lifecycle.r-lib.org/articles/stages.html#stable) | [![](https://github.com/RMI-PACTA/pacta.portfolio.import/actions/workflows/R-CMD-check.yaml/badge.svg?branch=main)](https://github.com/RMI-PACTA/pacta.portfolio.import/actions/workflows/R-CMD-check.yaml?query=branch%3Amain) | [![](https://img.shields.io/codecov/c/github/rmi-pacta/pacta.portfolio.import/main)](https://app.codecov.io/gh/RMI-PACTA/pacta.portfolio.import?branch=main) | [![](https://rmi-pacta.r-universe.dev/badges/pacta.portfolio.import)](https://rmi-pacta.r-universe.dev/pacta.portfolio.import) | [![](https://www.r-pkg.org/badges/version/pacta.portfolio.import)](https://CRAN.R-project.org/package=pacta.portfolio.import) | [![](https://img.shields.io/github/r-package/v/rmi-pacta/pacta.portfolio.import/main?label=version&amp;labelColor=%23444d56&amp;color=%2334d058)](https://github.com/RMI-PACTA/pacta.portfolio.import/blob/main/DESCRIPTION) | [![](https://img.shields.io/badge/dynamic/json?label=codeowner&amp;query=codeownerInfo.ownersForFile&amp;url=https%3A%2F%2Fgithub.com%2Frmi-pacta%2Fpacta.portfolio.import%2Fdeferred-metadata%2Fmain%2F.github%2FCODEOWNERS)](https://github.com/RMI-PACTA/pacta.portfolio.import/blob/main/.github/CODEOWNERS) |
| [pacta.data.validation](https://rmi-pacta.github.io/pacta.data.validation/) | [![](https://img.shields.io/badge/lifecycle-stable-none.svg?labelColor=%23444d56&amp;color=%2334d058)](https://lifecycle.r-lib.org/articles/stages.html#stable) | [![](https://github.com/RMI-PACTA/pacta.data.validation/actions/workflows/R-CMD-check.yaml/badge.svg?branch=main)](https://github.com/RMI-PACTA/pacta.data.validation/actions/workflows/R-CMD-check.yaml?query=branch%3Amain) | [![](https://img.shields.io/codecov/c/github/rmi-pacta/pacta.data.validation/main)](https://app.codecov.io/gh/RMI-PACTA/pacta.data.validation?branch=main) | [![](https://rmi-pacta.r-universe.dev/badges/pacta.data.validation)](https://rmi-pacta.r-universe.dev/pacta.data.validation) | [![](https://www.r-pkg.org/badges/version/pacta.data.validation)](https://CRAN.R-project.org/package=pacta.data.validation) | [![](https://img.shields.io/github/r-package/v/rmi-pacta/pacta.data.validation/main?label=version&amp;labelColor=%23444d56&amp;color=%2334d058)](https://github.com/RMI-PACTA/pacta.data.validation/blob/main/DESCRIPTION) | [![](https://img.shields.io/badge/dynamic/json?label=codeowner&amp;query=codeownerInfo.ownersForFile&amp;url=https%3A%2F%2Fgithub.com%2Frmi-pacta%2Fpacta.data.validation%2Fdeferred-metadata%2Fmain%2F.github%2FCODEOWNERS)](https://github.com/RMI-PACTA/pacta.data.validation/blob/main/.github/CODEOWNERS) |
| [pacta.portfolio.allocate](https://rmi-pacta.github.io/pacta.portfolio.allocate/) | [![](https://img.shields.io/badge/lifecycle-stable-none.svg?labelColor=%23444d56&amp;color=%2334d058)](https://lifecycle.r-lib.org/articles/stages.html#stable) | [![](https://github.com/RMI-PACTA/pacta.portfolio.allocate/actions/workflows/R-CMD-check.yaml/badge.svg?branch=main)](https://github.com/RMI-PACTA/pacta.portfolio.allocate/actions/workflows/R-CMD-check.yaml?query=branch%3Amain) | [![](https://img.shields.io/codecov/c/github/rmi-pacta/pacta.portfolio.allocate/main)](https://app.codecov.io/gh/RMI-PACTA/pacta.portfolio.allocate?branch=main) | [![](https://rmi-pacta.r-universe.dev/badges/pacta.portfolio.allocate)](https://rmi-pacta.r-universe.dev/pacta.portfolio.allocate) | [![](https://www.r-pkg.org/badges/version/pacta.portfolio.allocate)](https://CRAN.R-project.org/package=pacta.portfolio.allocate) | [![](https://img.shields.io/github/r-package/v/rmi-pacta/pacta.portfolio.allocate/main?label=version&amp;labelColor=%23444d56&amp;color=%2334d058)](https://github.com/RMI-PACTA/pacta.portfolio.allocate/blob/main/DESCRIPTION) | [![](https://img.shields.io/badge/dynamic/json?label=codeowner&amp;query=codeownerInfo.ownersForFile&amp;url=https%3A%2F%2Fgithub.com%2Frmi-pacta%2Fpacta.portfolio.allocate%2Fdeferred-metadata%2Fmain%2F.github%2FCODEOWNERS)](https://github.com/RMI-PACTA/pacta.portfolio.allocate/blob/main/.github/CODEOWNERS) |
| [pacta.portfolio.audit](https://rmi-pacta.github.io/pacta.portfolio.audit/) | [![](https://img.shields.io/badge/lifecycle-stable-none.svg?labelColor=%23444d56&amp;color=%2334d058)](https://lifecycle.r-lib.org/articles/stages.html#stable) | [![](https://github.com/RMI-PACTA/pacta.portfolio.audit/actions/workflows/R-CMD-check.yaml/badge.svg?branch=main)](https://github.com/RMI-PACTA/pacta.portfolio.audit/actions/workflows/R-CMD-check.yaml?query=branch%3Amain) | [![](https://img.shields.io/codecov/c/github/rmi-pacta/pacta.portfolio.audit/main)](https://app.codecov.io/gh/RMI-PACTA/pacta.portfolio.audit?branch=main) | [![](https://rmi-pacta.r-universe.dev/badges/pacta.portfolio.audit)](https://rmi-pacta.r-universe.dev/pacta.portfolio.audit) | [![](https://www.r-pkg.org/badges/version/pacta.portfolio.audit)](https://CRAN.R-project.org/package=pacta.portfolio.audit) | [![](https://img.shields.io/github/r-package/v/rmi-pacta/pacta.portfolio.audit/main?label=version&amp;labelColor=%23444d56&amp;color=%2334d058)](https://github.com/RMI-PACTA/pacta.portfolio.audit/blob/main/DESCRIPTION) | [![](https://img.shields.io/badge/dynamic/json?label=codeowner&amp;query=codeownerInfo.ownersForFile&amp;url=https%3A%2F%2Fgithub.com%2Frmi-pacta%2Fpacta.portfolio.audit%2Fdeferred-metadata%2Fmain%2F.github%2FCODEOWNERS)](https://github.com/RMI-PACTA/pacta.portfolio.audit/blob/main/.github/CODEOWNERS) |
| [pacta.portfolio.report](https://rmi-pacta.github.io/pacta.portfolio.report/) | [![](https://img.shields.io/badge/lifecycle-stable-none.svg?labelColor=%23444d56&amp;color=%2334d058)](https://lifecycle.r-lib.org/articles/stages.html#stable) | [![](https://github.com/RMI-PACTA/pacta.portfolio.report/actions/workflows/R-CMD-check.yaml/badge.svg?branch=main)](https://github.com/RMI-PACTA/pacta.portfolio.report/actions/workflows/R-CMD-check.yaml?query=branch%3Amain) | [![](https://img.shields.io/codecov/c/github/rmi-pacta/pacta.portfolio.report/main)](https://app.codecov.io/gh/RMI-PACTA/pacta.portfolio.report?branch=main) | [![](https://rmi-pacta.r-universe.dev/badges/pacta.portfolio.report)](https://rmi-pacta.r-universe.dev/pacta.portfolio.report) | [![](https://www.r-pkg.org/badges/version/pacta.portfolio.report)](https://CRAN.R-project.org/package=pacta.portfolio.report) | [![](https://img.shields.io/github/r-package/v/rmi-pacta/pacta.portfolio.report/main?label=version&amp;labelColor=%23444d56&amp;color=%2334d058)](https://github.com/RMI-PACTA/pacta.portfolio.report/blob/main/DESCRIPTION) | [![](https://img.shields.io/badge/dynamic/json?label=codeowner&amp;query=codeownerInfo.ownersForFile&amp;url=https%3A%2F%2Fgithub.com%2Frmi-pacta%2Fpacta.portfolio.report%2Fdeferred-metadata%2Fmain%2F.github%2FCODEOWNERS)](https://github.com/RMI-PACTA/pacta.portfolio.report/blob/main/.github/CODEOWNERS) |
| [pacta.portfolio.utils](https://rmi-pacta.github.io/pacta.portfolio.utils/) | [![](https://img.shields.io/badge/lifecycle-stable-none.svg?labelColor=%23444d56&amp;color=%2334d058)](https://lifecycle.r-lib.org/articles/stages.html#stable) | [![](https://github.com/RMI-PACTA/pacta.portfolio.utils/actions/workflows/R-CMD-check.yaml/badge.svg?branch=main)](https://github.com/RMI-PACTA/pacta.portfolio.utils/actions/workflows/R-CMD-check.yaml?query=branch%3Amain) | [![](https://img.shields.io/codecov/c/github/rmi-pacta/pacta.portfolio.utils/main)](https://app.codecov.io/gh/RMI-PACTA/pacta.portfolio.utils?branch=main) | [![](https://rmi-pacta.r-universe.dev/badges/pacta.portfolio.utils)](https://rmi-pacta.r-universe.dev/pacta.portfolio.utils) | [![](https://www.r-pkg.org/badges/version/pacta.portfolio.utils)](https://CRAN.R-project.org/package=pacta.portfolio.utils) | [![](https://img.shields.io/github/r-package/v/rmi-pacta/pacta.portfolio.utils/main?label=version&amp;labelColor=%23444d56&amp;color=%2334d058)](https://github.com/RMI-PACTA/pacta.portfolio.utils/blob/main/DESCRIPTION) | [![](https://img.shields.io/badge/dynamic/json?label=codeowner&amp;query=codeownerInfo.ownersForFile&amp;url=https%3A%2F%2Fgithub.com%2Frmi-pacta%2Fpacta.portfolio.utils%2Fdeferred-metadata%2Fmain%2F.github%2FCODEOWNERS)](https://github.com/RMI-PACTA/pacta.portfolio.utils/blob/main/.github/CODEOWNERS) |
| [pacta.executive.summary](https://rmi-pacta.github.io/pacta.executive.summary/) | [![](https://img.shields.io/badge/lifecycle-stable-none.svg?labelColor=%23444d56&amp;color=%2334d058)](https://lifecycle.r-lib.org/articles/stages.html#stable) | [![](https://github.com/RMI-PACTA/pacta.executive.summary/actions/workflows/R-CMD-check.yaml/badge.svg?branch=main)](https://github.com/RMI-PACTA/pacta.executive.summary/actions/workflows/R-CMD-check.yaml?query=branch%3Amain) | [![](https://img.shields.io/codecov/c/github/rmi-pacta/pacta.executive.summary/main)](https://app.codecov.io/gh/RMI-PACTA/pacta.executive.summary?branch=main) | [![](https://rmi-pacta.r-universe.dev/badges/pacta.executive.summary)](https://rmi-pacta.r-universe.dev/pacta.executive.summary) | [![](https://www.r-pkg.org/badges/version/pacta.executive.summary)](https://CRAN.R-project.org/package=pacta.executive.summary) | [![](https://img.shields.io/github/r-package/v/rmi-pacta/pacta.executive.summary/main?label=version&amp;labelColor=%23444d56&amp;color=%2334d058)](https://github.com/RMI-PACTA/pacta.executive.summary/blob/main/DESCRIPTION) | [![](https://img.shields.io/badge/dynamic/json?label=codeowner&amp;query=codeownerInfo.ownersForFile&amp;url=https%3A%2F%2Fgithub.com%2Frmi-pacta%2Fpacta.executive.summary%2Fdeferred-metadata%2Fmain%2F.github%2FCODEOWNERS)](https://github.com/RMI-PACTA/pacta.executive.summary/blob/main/.github/CODEOWNERS) |
| [pacta.interactive.plot](https://rmi-pacta.github.io/pacta.interactive.plot/) | [![](https://img.shields.io/badge/lifecycle-stable-none.svg?labelColor=%23444d56&amp;color=%2334d058)](https://lifecycle.r-lib.org/articles/stages.html#stable) | [![](https://github.com/RMI-PACTA/pacta.interactive.plot/actions/workflows/R-CMD-check.yaml/badge.svg?branch=main)](https://github.com/RMI-PACTA/pacta.interactive.plot/actions/workflows/R-CMD-check.yaml?query=branch%3Amain) | [![](https://img.shields.io/codecov/c/github/rmi-pacta/pacta.interactive.plot/main)](https://app.codecov.io/gh/RMI-PACTA/pacta.interactive.plot?branch=main) | [![](https://rmi-pacta.r-universe.dev/badges/pacta.interactive.plot)](https://rmi-pacta.r-universe.dev/pacta.interactive.plot) | [![](https://www.r-pkg.org/badges/version/pacta.interactive.plot)](https://CRAN.R-project.org/package=pacta.interactive.plot) | [![](https://img.shields.io/github/r-package/v/rmi-pacta/pacta.interactive.plot/main?label=version&amp;labelColor=%23444d56&amp;color=%2334d058)](https://github.com/RMI-PACTA/pacta.interactive.plot/blob/main/DESCRIPTION) | [![](https://img.shields.io/badge/dynamic/json?label=codeowner&amp;query=codeownerInfo.ownersForFile&amp;url=https%3A%2F%2Fgithub.com%2Frmi-pacta%2Fpacta.interactive.plot%2Fdeferred-metadata%2Fmain%2F.github%2FCODEOWNERS)](https://github.com/RMI-PACTA/pacta.interactive.plot/blob/main/.github/CODEOWNERS) |

**Comment by jdhoffa** [comment]
looks good to me!!
