### ISSUE TITLE
pkgdown: consider adding a PR preview option

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pactaverse#49]
Relates to https://github.com/RMI-PACTA/pacta-dashboard-svelte/pull/137#pullrequestreview-2484718242

Would allow us to test changes to the pkgdown site easily without merging to `main`. 
Might be relevant to every `pactaverse` package as well.

**Comment by cjyetman** [comment]
have to make sure it doesn't mess with the `dev` and `release` versions of the `pkgdown` sites, and make it sure it plays nice with (and/or doesn't get obliterated by) `pkgdown`'s management of wiping everything in `gh-pages` (see e.g. https://github.com/RMI-PACTA/r2dii.match/pull/506)
